name: Build and Test

on: [push]

jobs:
  client:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test-ci
        env:
          CI: true
  deploy:
    needs: [client]
    name: 'Deploy to Github Pages'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: 'Export folder'
        run: npm run export