name: Build, Test, Deploy

on: [push]

jobs:
  client:
    name: 'Build, Test, Deploy'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test-ci
        env:
          CI: true
      - name: 'Build Nextjs'
        run: npm run build
      - name: 'Export folder'
        run: npm run export
      if: github.ref == 'refs/heads/main'
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.

